const data = {
  date: '2022-07-21',
  boat_time: '00:00',
  period: '-',
  departure: '00:00',
  arrival: '00:00',
  boat_size: '-',
  gps_no: '1',
  guide: '-',
  recorder: '-',
  sighting: '-',
  sighting_id: '',
  observations: '-',
  weather: '-',
  wind_direction: '-',
  wave_condition: '-',
  current: '-',
  latitude: '-',
  latitude_min: '',
  latitude_sec: '',
  longitude: '-',
  longitude_min: '',
  longitude_sec: '',
  boat_number: '',
  sighting_method: '-',
  dorsal_fin: '0',
  exhalation: '0',
  splash: '0',
  exhibition: '0',
  approach_time: '-',
  approach_gps_no: '',
  leaving_time: '-',
  leaving_gps_no: '',
  leaving_method: '-',
  dolphin_type: '-',
  type_confirmation: '-',
  dolphin_group_no: '',
  dolphin_type_no: '',
  mother_child: '-',
  mix: '-',
  mix_type: '-',
  time: ['0-10', '11-20', '21-30'],
  boat_interaction: ['-', '-', '-'],
  boat_distance: ['', '', ''],
  group_closeness_close: ['0', '0', '0'],
  group_closeness_normal: ['0', '0', '0'],
  group_closeness_spreaded: ['0', '0', '0'],
  speed_slow: ['0', '0', '0'],
  speed_moderate: ['0', '0', '0'],
  speed_fast: ['0', '0', '0'],
  speed_resting: ['0', '0', '0'],
  speed_circling: ['0', '0', '0'],
  foraging_maybe: ['0', '0', '0'],
  foraging_sure: ['0', '0', '0'],
  mating: ['0', '0', '0'],
  splash_interaction: ['0', '0', '0'],
  snorkel: ['0', '0', '0'],
  racing: ['0', '0', '0'],
  jump: ['0', '0', '0'],
  surfing_artificial: ['0', '0', '0'],
  surfing: ['0', '0', '0'],
  tail_lift: ['0', '0', '0'],
  contact: ['0', '0', '0'],
  backstroke: ['0', '0', '0'],
  boat_no: ['', '', ''],
  other: ['-', '-', '-'],
};

// const sailingInfoData = {
//     sailing_id: 201612311400,
//     sighting_id: 1,
//     mix: 1,
//     dolphin_type: 'Gm',
//     year: 2016,
//     month: 12,
//     day: 31,
//     period: 2,
//     departure: '14:10',
//     arrival: '15:59',
//     boat_size: 's',
//     sighting: 1,
//     gps_no: 2,
//     guide: '譚凱聰',
//     recorder: 'null',
//     observations: '有一隻左背上有圓形傷口，觀察中途，一次仰式打水，寶寶數次練習轉圈',
//     weather: null,
//     wind_direction: null,
//     wave_condition: null,
//     current: null
// };

// const obvGPS = {
//     id: 16,
//     obv_id: 5272,
//     latitude: 24,
//     latitude_min: 3,
//     latitude_sec: 328,
//     longitude: 121,
//     longitude_min: 39,
//     longitude_sec: 661
// }

// const obvApproach = {
//     id: 16,
//     obv_id: 5272,
//     approach_time: '14:35',
//     approach_gps_no: 1411,
//     leaving_time: '14:57',
//     leaving_gps_no: 1412,
//     leaving_method: 1
// }

// const obvDetail = {
//     id: 16,
//     obv_id: 5272,
//     sighting_method: 2,
//     dolphin_type: 'Gm',
//     type_confirmation: 1,
//     dolphin_group_no: 2,
//     dolphin_type_no: 2,
//     dorsal_fin: 1,
//     exhalation: 0,
//     splash: 0,
//     exhibition: 0,
//     mother_child: 1,
//     mother_child_no:  2,
//     group_size_lowest: 80,
//     group_size_probable: 100,
//     group_size_highest: 120,
//     mix: 1,
//     mix_type: 1
// }

// const obvInteraction = {
//     id: 16,
//     obv_id: 5272,
//     time1: 0-10,
//     boat_interaction1: 1,
//     boat_distance1: 1,
//     group_closeness_normal1: 0,
//     group_closeness_spreaded1: 1,
//     group_closeness_close1: 0,
//     speed_slow1: 0,
//     speed_moderate1: 1,
//     speed_fast1: 0,
//     speed_resting1: 0,
//     speed_circling1: 0,
//     foraging_maybe1: 0,
//     foraging_sure1: 0,
//     mating1: 0,
//     splash_interaction1: 0,
//     snorkel1: 0,
//     racing1: 0,
//     jump1: 0,
//     surfing_artificial1: 0,
//     surfing1: 0,
//     tail_lift1: 0,
//     contact1: 0,
//     backstroke1: 1,
//     boat_no1: 1,
//     other1: null,
//     time2: 11-20,
//     boat_interaction2: 1,
//     boat_distance2: 1,
//     group_closeness_normal2: 0,
//     group_closeness_spreaded2: 1,
//     group_closeness_close2: 0,
//     speed_slow2: 0,
//     speed_moderate2: 1,
//     speed_fast2: 0,
//     speed_resting2: 0,
//     speed_circling2: 0,
//     foraging_maybe2: 0,
//     foraging_sure2: 0,
//     mating2: 0,
//     splash_interaction2: 0,
//     snorkel2: 0,
//     racing2: 0,
//     jump2: 0,
//     surfing_artificial2: 0,
//     surfing2: 0,
//     tail_lift2: 0,
//     contact2: 0,
//     backstroke2: 1,
//     boat_no2: 1,
//     other2: null,
//     time3: 21-30,
//     boat_interaction3: 1,
//     boat_distance3: 1,
//     group_closeness_normal3: 0,
//     group_closeness_spreaded3: 1,
//     group_closeness_close3: 0,
//     speed_slow3: 0,
//     speed_moderate3: 1,
//     speed_fast3: 0,
//     speed_resting3: 0,
//     speed_circling3: 0,
//     foraging_maybe3: 0,
//     foraging_sure3: 0,
//     mating3: 0,
//     splash_interaction3: 0,
//     snorkel3: 0,
//     racing3: 0,
//     jump3: 0,
//     surfing_artificial3: 0,
//     surfing3: 0,
//     tail_lift3: 0,
//     contact3: 0,
//     backstroke3: 1,
//     boat_no3: 1,
//     other3: null
// }

module.exports = {
  data,
};
