version: "3.8"
services:
  dolphin-tracker: 
    build: .
    container_name: "dolphin-tracker"
    env_file:
      - .env
    networks:
      - my-net
  nginx_dolphin-tracker: 
    image: "nginx:stable-alpine"
    container_name: "nginx"
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: always
    networks:
      - my-net

networks:
  my-net:
    driver: bridge